# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rework_temp.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataResamplingTools(object):
    def setupUi(self, DataResamplingTools):
        DataResamplingTools.setObjectName("DataResamplingTools")
        DataResamplingTools.resize(740, 741)
        self.centralwidget = QtWidgets.QWidget(DataResamplingTools)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dataTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.dataTab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(60, 91))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.datasetButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetButton.sizePolicy().hasHeightForWidth())
        self.datasetButton.setSizePolicy(sizePolicy)
        self.datasetButton.setMinimumSize(QtCore.QSize(0, 0))
        self.datasetButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.datasetButton.setObjectName("datasetButton")
        self.horizontalLayout.addWidget(self.datasetButton)
        self.datasetLoadingTextLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetLoadingTextLabel.sizePolicy().hasHeightForWidth())
        self.datasetLoadingTextLabel.setSizePolicy(sizePolicy)
        self.datasetLoadingTextLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.datasetLoadingTextLabel.setMaximumSize(QtCore.QSize(50, 91))
        self.datasetLoadingTextLabel.setText("")
        self.datasetLoadingTextLabel.setObjectName("datasetLoadingTextLabel")
        self.horizontalLayout.addWidget(self.datasetLoadingTextLabel)
        self.datasetProgressBar = QtWidgets.QProgressBar(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetProgressBar.sizePolicy().hasHeightForWidth())
        self.datasetProgressBar.setSizePolicy(sizePolicy)
        self.datasetProgressBar.setMinimumSize(QtCore.QSize(100, 0))
        self.datasetProgressBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.datasetProgressBar.setAcceptDrops(False)
        self.datasetProgressBar.setMaximum(336)
        self.datasetProgressBar.setProperty("value", 0)
        self.datasetProgressBar.setObjectName("datasetProgressBar")
        self.horizontalLayout.addWidget(self.datasetProgressBar)
        self.filePathLabel = QtWidgets.QLabel(self.groupBox)
        self.filePathLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePathLabel.sizePolicy().hasHeightForWidth())
        self.filePathLabel.setSizePolicy(sizePolicy)
        self.filePathLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.filePathLabel.setMaximumSize(QtCore.QSize(47, 91))
        self.filePathLabel.setText("")
        self.filePathLabel.setObjectName("filePathLabel")
        self.horizontalLayout.addWidget(self.filePathLabel)
        self.datasetPickedLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetPickedLabel.sizePolicy().hasHeightForWidth())
        self.datasetPickedLabel.setSizePolicy(sizePolicy)
        self.datasetPickedLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.datasetPickedLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.datasetPickedLabel.setText("")
        self.datasetPickedLabel.setWordWrap(True)
        self.datasetPickedLabel.setObjectName("datasetPickedLabel")
        self.horizontalLayout.addWidget(self.datasetPickedLabel)
        self.datasetLoadingResultLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetLoadingResultLabel.sizePolicy().hasHeightForWidth())
        self.datasetLoadingResultLabel.setSizePolicy(sizePolicy)
        self.datasetLoadingResultLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.datasetLoadingResultLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.datasetLoadingResultLabel.setText("")
        self.datasetLoadingResultLabel.setIndent(-1)
        self.datasetLoadingResultLabel.setObjectName("datasetLoadingResultLabel")
        self.horizontalLayout.addWidget(self.datasetLoadingResultLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(169, 91))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.dataTableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.dataTableWidget.setObjectName("dataTableWidget")
        self.dataTableWidget.setColumnCount(0)
        self.dataTableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.dataTableWidget)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(160, 0))
        self.label_11.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_22.addWidget(self.label_11)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_22.addWidget(self.label_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(85, 0))
        self.label_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_23.addWidget(self.label_17)
        self.totalNumberOfExamplesLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalNumberOfExamplesLabel.sizePolicy().hasHeightForWidth())
        self.totalNumberOfExamplesLabel.setSizePolicy(sizePolicy)
        self.totalNumberOfExamplesLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.totalNumberOfExamplesLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.totalNumberOfExamplesLabel.setText("")
        self.totalNumberOfExamplesLabel.setObjectName("totalNumberOfExamplesLabel")
        self.horizontalLayout_23.addWidget(self.totalNumberOfExamplesLabel)
        self.pieChartNormalDataset = QtWidgets.QPushButton(self.groupBox)
        self.pieChartNormalDataset.setObjectName("pieChartNormalDataset")
        self.horizontalLayout_23.addWidget(self.pieChartNormalDataset)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(85, 0))
        self.label_18.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_24.addWidget(self.label_18)
        self.numberOfPositivexamplesLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfPositivexamplesLabel.sizePolicy().hasHeightForWidth())
        self.numberOfPositivexamplesLabel.setSizePolicy(sizePolicy)
        self.numberOfPositivexamplesLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.numberOfPositivexamplesLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.numberOfPositivexamplesLabel.setText("")
        self.numberOfPositivexamplesLabel.setObjectName("numberOfPositivexamplesLabel")
        self.horizontalLayout_24.addWidget(self.numberOfPositivexamplesLabel)
        self.pairPlotNormalDataset = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pairPlotNormalDataset.sizePolicy().hasHeightForWidth())
        self.pairPlotNormalDataset.setSizePolicy(sizePolicy)
        self.pairPlotNormalDataset.setObjectName("pairPlotNormalDataset")
        self.horizontalLayout_24.addWidget(self.pairPlotNormalDataset)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_73 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setMinimumSize(QtCore.QSize(85, 0))
        self.label_73.setMaximumSize(QtCore.QSize(58, 16777215))
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_25.addWidget(self.label_73, 0, QtCore.Qt.AlignLeft)
        self.targetClassPercentageLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetClassPercentageLabel.sizePolicy().hasHeightForWidth())
        self.targetClassPercentageLabel.setSizePolicy(sizePolicy)
        self.targetClassPercentageLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.targetClassPercentageLabel.setMaximumSize(QtCore.QSize(30, 16777215))
        self.targetClassPercentageLabel.setText("")
        self.targetClassPercentageLabel.setObjectName("targetClassPercentageLabel")
        self.horizontalLayout_25.addWidget(self.targetClassPercentageLabel)
        self.standardGraphNormalDataset = QtWidgets.QPushButton(self.groupBox)
        self.standardGraphNormalDataset.setObjectName("standardGraphNormalDataset")
        self.horizontalLayout_25.addWidget(self.standardGraphNormalDataset)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_74 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setMinimumSize(QtCore.QSize(85, 0))
        self.label_74.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_26.addWidget(self.label_74)
        self.imbalancedRatioLabel = QtWidgets.QLabel(self.groupBox)
        self.imbalancedRatioLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.imbalancedRatioLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imbalancedRatioLabel.setText("")
        self.imbalancedRatioLabel.setObjectName("imbalancedRatioLabel")
        self.horizontalLayout_26.addWidget(self.imbalancedRatioLabel)
        self.pcaGraphNormalDataset = QtWidgets.QPushButton(self.groupBox)
        self.pcaGraphNormalDataset.setObjectName("pcaGraphNormalDataset")
        self.horizontalLayout_26.addWidget(self.pcaGraphNormalDataset)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dataTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(160, 0))
        self.label_3.setMaximumSize(QtCore.QSize(160, 91))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.resamplingAlgorithms = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resamplingAlgorithms.sizePolicy().hasHeightForWidth())
        self.resamplingAlgorithms.setSizePolicy(sizePolicy)
        self.resamplingAlgorithms.setMinimumSize(QtCore.QSize(150, 0))
        self.resamplingAlgorithms.setMaximumSize(QtCore.QSize(150, 16777215))
        self.resamplingAlgorithms.setObjectName("resamplingAlgorithms")
        self.horizontalLayout_6.addWidget(self.resamplingAlgorithms)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(160, 0))
        self.label_32.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_4.addWidget(self.label_32)
        self.outputDirectoryButton = QtWidgets.QPushButton(self.groupBox_2)
        self.outputDirectoryButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.outputDirectoryButton.setObjectName("outputDirectoryButton")
        self.horizontalLayout_4.addWidget(self.outputDirectoryButton)
        self.outputDirectoryPickedLabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDirectoryPickedLabel.sizePolicy().hasHeightForWidth())
        self.outputDirectoryPickedLabel.setSizePolicy(sizePolicy)
        self.outputDirectoryPickedLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.outputDirectoryPickedLabel.setText("")
        self.outputDirectoryPickedLabel.setWordWrap(True)
        self.outputDirectoryPickedLabel.setObjectName("outputDirectoryPickedLabel")
        self.horizontalLayout_4.addWidget(self.outputDirectoryPickedLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.startButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(90, 0))
        self.startButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_5.addWidget(self.startButton)
        spacerItem7 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.resampleProgressBar = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resampleProgressBar.sizePolicy().hasHeightForWidth())
        self.resampleProgressBar.setSizePolicy(sizePolicy)
        self.resampleProgressBar.setProperty("value", 0)
        self.resampleProgressBar.setObjectName("resampleProgressBar")
        self.horizontalLayout_5.addWidget(self.resampleProgressBar)
        self.samplingResultLabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.samplingResultLabel.sizePolicy().hasHeightForWidth())
        self.samplingResultLabel.setSizePolicy(sizePolicy)
        self.samplingResultLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.samplingResultLabel.setText("")
        self.samplingResultLabel.setObjectName("samplingResultLabel")
        self.horizontalLayout_5.addWidget(self.samplingResultLabel)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setMinimumSize(QtCore.QSize(160, 0))
        self.label_6.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setMinimumSize(QtCore.QSize(85, 0))
        self.label_36.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_27.addWidget(self.label_36)
        self.totalNumberOfExamplesResampledLabel = QtWidgets.QLabel(self.groupBox_2)
        self.totalNumberOfExamplesResampledLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.totalNumberOfExamplesResampledLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.totalNumberOfExamplesResampledLabel.setText("")
        self.totalNumberOfExamplesResampledLabel.setObjectName("totalNumberOfExamplesResampledLabel")
        self.horizontalLayout_27.addWidget(self.totalNumberOfExamplesResampledLabel)
        self.pieChartResampledDataset = QtWidgets.QPushButton(self.groupBox_2)
        self.pieChartResampledDataset.setObjectName("pieChartResampledDataset")
        self.horizontalLayout_27.addWidget(self.pieChartResampledDataset)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setMinimumSize(QtCore.QSize(85, 0))
        self.label_28.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_28.addWidget(self.label_28)
        self.numberOfPositiveExamplesResampledLabel = QtWidgets.QLabel(self.groupBox_2)
        self.numberOfPositiveExamplesResampledLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.numberOfPositiveExamplesResampledLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.numberOfPositiveExamplesResampledLabel.setText("")
        self.numberOfPositiveExamplesResampledLabel.setObjectName("numberOfPositiveExamplesResampledLabel")
        self.horizontalLayout_28.addWidget(self.numberOfPositiveExamplesResampledLabel)
        self.pairPlotResampledDataset = QtWidgets.QPushButton(self.groupBox_2)
        self.pairPlotResampledDataset.setObjectName("pairPlotResampledDataset")
        self.horizontalLayout_28.addWidget(self.pairPlotResampledDataset)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_84 = QtWidgets.QLabel(self.groupBox_2)
        self.label_84.setMinimumSize(QtCore.QSize(85, 0))
        self.label_84.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_84.setObjectName("label_84")
        self.horizontalLayout_29.addWidget(self.label_84)
        self.targetClassPercentageResampledLabel = QtWidgets.QLabel(self.groupBox_2)
        self.targetClassPercentageResampledLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.targetClassPercentageResampledLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.targetClassPercentageResampledLabel.setText("")
        self.targetClassPercentageResampledLabel.setObjectName("targetClassPercentageResampledLabel")
        self.horizontalLayout_29.addWidget(self.targetClassPercentageResampledLabel)
        self.standardGraphResampledDataset = QtWidgets.QPushButton(self.groupBox_2)
        self.standardGraphResampledDataset.setObjectName("standardGraphResampledDataset")
        self.horizontalLayout_29.addWidget(self.standardGraphResampledDataset)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_85 = QtWidgets.QLabel(self.groupBox_2)
        self.label_85.setMinimumSize(QtCore.QSize(85, 0))
        self.label_85.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_85.setObjectName("label_85")
        self.horizontalLayout_30.addWidget(self.label_85)
        self.imbalancedRatioResampledLabel = QtWidgets.QLabel(self.groupBox_2)
        self.imbalancedRatioResampledLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.imbalancedRatioResampledLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imbalancedRatioResampledLabel.setText("")
        self.imbalancedRatioResampledLabel.setObjectName("imbalancedRatioResampledLabel")
        self.horizontalLayout_30.addWidget(self.imbalancedRatioResampledLabel)
        self.pcaGraphResampledDataset = QtWidgets.QPushButton(self.groupBox_2)
        self.pcaGraphResampledDataset.setObjectName("pcaGraphResampledDataset")
        self.horizontalLayout_30.addWidget(self.pcaGraphResampledDataset)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_30)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.dataTab, "")
        self.testsTab = QtWidgets.QWidget()
        self.testsTab.setObjectName("testsTab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.testsTab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_5 = QtWidgets.QGroupBox(self.testsTab)
        self.groupBox_5.setMaximumSize(QtCore.QSize(1233333, 228))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_63 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setMinimumSize(QtCore.QSize(0, 0))
        self.label_63.setMaximumSize(QtCore.QSize(90, 50))
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_12.addWidget(self.label_63)
        spacerItem14 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.selectedDatasetExperimentsTab = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedDatasetExperimentsTab.sizePolicy().hasHeightForWidth())
        self.selectedDatasetExperimentsTab.setSizePolicy(sizePolicy)
        self.selectedDatasetExperimentsTab.setMinimumSize(QtCore.QSize(250, 0))
        self.selectedDatasetExperimentsTab.setMaximumSize(QtCore.QSize(250, 16777215))
        self.selectedDatasetExperimentsTab.setObjectName("selectedDatasetExperimentsTab")
        self.horizontalLayout_12.addWidget(self.selectedDatasetExperimentsTab)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_64 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setMinimumSize(QtCore.QSize(135, 0))
        self.label_64.setMaximumSize(QtCore.QSize(135, 91))
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_13.addWidget(self.label_64)
        self.classAlgorithms = QtWidgets.QComboBox(self.groupBox_5)
        self.classAlgorithms.setMinimumSize(QtCore.QSize(175, 0))
        self.classAlgorithms.setMaximumSize(QtCore.QSize(150, 16777215))
        self.classAlgorithms.setObjectName("classAlgorithms")
        self.horizontalLayout_13.addWidget(self.classAlgorithms)
        spacerItem16 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem16)
        self.classifyButton = QtWidgets.QPushButton(self.groupBox_5)
        self.classifyButton.setObjectName("classifyButton")
        self.horizontalLayout_13.addWidget(self.classifyButton)
        self.clearGraphs = QtWidgets.QPushButton(self.groupBox_5)
        self.clearGraphs.setObjectName("clearGraphs")
        self.horizontalLayout_13.addWidget(self.clearGraphs)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem17)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_65 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setMinimumSize(QtCore.QSize(135, 0))
        self.label_65.setMaximumSize(QtCore.QSize(135, 91))
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_14.addWidget(self.label_65)
        self.resamplingAlgorithmsExperimentsCase = QtWidgets.QComboBox(self.groupBox_5)
        self.resamplingAlgorithmsExperimentsCase.setMinimumSize(QtCore.QSize(175, 0))
        self.resamplingAlgorithmsExperimentsCase.setMaximumSize(QtCore.QSize(150, 16777215))
        self.resamplingAlgorithmsExperimentsCase.setObjectName("resamplingAlgorithmsExperimentsCase")
        self.horizontalLayout_14.addWidget(self.resamplingAlgorithmsExperimentsCase)
        spacerItem18 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem18)
        self.label_67 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        self.label_67.setMinimumSize(QtCore.QSize(186, 0))
        self.label_67.setMaximumSize(QtCore.QSize(186, 50))
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_14.addWidget(self.label_67)
        self.normalClassifyProgressBar = QtWidgets.QProgressBar(self.groupBox_5)
        self.normalClassifyProgressBar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.normalClassifyProgressBar.setSizeIncrement(QtCore.QSize(0, 0))
        self.normalClassifyProgressBar.setMaximum(10)
        self.normalClassifyProgressBar.setProperty("value", 0)
        self.normalClassifyProgressBar.setObjectName("normalClassifyProgressBar")
        self.horizontalLayout_14.addWidget(self.normalClassifyProgressBar)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem19)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_66 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setMinimumSize(QtCore.QSize(135, 0))
        self.label_66.setMaximumSize(QtCore.QSize(135, 91))
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_16.addWidget(self.label_66)
        self.numberOfFoldsCV = QtWidgets.QComboBox(self.groupBox_5)
        self.numberOfFoldsCV.setMinimumSize(QtCore.QSize(35, 0))
        self.numberOfFoldsCV.setMaximumSize(QtCore.QSize(35, 16777215))
        self.numberOfFoldsCV.setCurrentText("")
        self.numberOfFoldsCV.setMaxVisibleItems(10)
        self.numberOfFoldsCV.setObjectName("numberOfFoldsCV")
        self.horizontalLayout_16.addWidget(self.numberOfFoldsCV)
        spacerItem20 = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem20)
        self.label_68 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_68.sizePolicy().hasHeightForWidth())
        self.label_68.setSizePolicy(sizePolicy)
        self.label_68.setMinimumSize(QtCore.QSize(186, 0))
        self.label_68.setMaximumSize(QtCore.QSize(186, 50))
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_16.addWidget(self.label_68)
        self.resampleClassifyProgressBar = QtWidgets.QProgressBar(self.groupBox_5)
        self.resampleClassifyProgressBar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.resampleClassifyProgressBar.setMaximum(10)
        self.resampleClassifyProgressBar.setProperty("value", 0)
        self.resampleClassifyProgressBar.setObjectName("resampleClassifyProgressBar")
        self.horizontalLayout_16.addWidget(self.resampleClassifyProgressBar)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem21)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.verticalLayout_11.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.testsTab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_69 = QtWidgets.QLabel(self.groupBox_4)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_13.addWidget(self.label_69)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_4)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 676, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_13.addWidget(self.scrollArea)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_13.addItem(spacerItem22)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.testsTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        DataResamplingTools.setCentralWidget(self.centralwidget)

        self.retranslateUi(DataResamplingTools)
        self.tabWidget.setCurrentIndex(1)
        self.numberOfFoldsCV.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(DataResamplingTools)

    def retranslateUi(self, DataResamplingTools):
        _translate = QtCore.QCoreApplication.translate
        DataResamplingTools.setWindowTitle(_translate("DataResamplingTools", "DataResamplingTools"))
        self.groupBox.setTitle(_translate("DataResamplingTools", "Original Data"))
        self.label_2.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.label_2.setText(_translate("DataResamplingTools", "Select a file:"))
        self.datasetButton.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.datasetButton.setText(_translate("DataResamplingTools", "..."))
        self.datasetLoadingTextLabel.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.filePathLabel.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.datasetLoadingResultLabel.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.label_4.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.label_4.setText(_translate("DataResamplingTools", "Table view"))
        self.label_11.setText(_translate("DataResamplingTools", "Basic Information"))
        self.label_9.setText(_translate("DataResamplingTools", "Graphics"))
        self.label_17.setText(_translate("DataResamplingTools", "# Examples:"))
        self.pieChartNormalDataset.setText(_translate("DataResamplingTools", "PieChart"))
        self.label_18.setText(_translate("DataResamplingTools", "# Pos. Ex.:"))
        self.pairPlotNormalDataset.setText(_translate("DataResamplingTools", "PairPlot"))
        self.label_73.setText(_translate("DataResamplingTools", "% Pos. Ex.:"))
        self.standardGraphNormalDataset.setText(_translate("DataResamplingTools", "Standard"))
        self.label_74.setText(_translate("DataResamplingTools", "Imbalanced ratio:"))
        self.pcaGraphNormalDataset.setText(_translate("DataResamplingTools", "PCA"))
        self.groupBox_2.setTitle(_translate("DataResamplingTools", "Re-sampled Data"))
        self.label_3.setText(_translate("DataResamplingTools", "Resampling Algorithm:"))
        self.label_32.setText(_translate("DataResamplingTools", "Output dir:"))
        self.outputDirectoryButton.setText(_translate("DataResamplingTools", "..."))
        self.startButton.setText(_translate("DataResamplingTools", "Start sampling"))
        self.label_6.setText(_translate("DataResamplingTools", "Basic Information"))
        self.label.setText(_translate("DataResamplingTools", "Graphics"))
        self.label_36.setText(_translate("DataResamplingTools", "# Examples"))
        self.pieChartResampledDataset.setText(_translate("DataResamplingTools", "PieChart"))
        self.label_28.setText(_translate("DataResamplingTools", "# Pos. Ex"))
        self.pairPlotResampledDataset.setText(_translate("DataResamplingTools", "PairPlot"))
        self.label_84.setText(_translate("DataResamplingTools", "% Pos. Ex."))
        self.standardGraphResampledDataset.setText(_translate("DataResamplingTools", "Standard"))
        self.label_85.setText(_translate("DataResamplingTools", "Imbalanced ratio"))
        self.pcaGraphResampledDataset.setText(_translate("DataResamplingTools", "PCA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), _translate("DataResamplingTools", "Data"))
        self.groupBox_5.setTitle(_translate("DataResamplingTools", "Test Controls and Progress"))
        self.label_63.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.label_63.setText(_translate("DataResamplingTools", "Selected dataset:"))
        self.selectedDatasetExperimentsTab.setText(_translate("DataResamplingTools", " "))
        self.label_64.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.label_64.setText(_translate("DataResamplingTools", "Choose classifier:"))
        self.classifyButton.setText(_translate("DataResamplingTools", "Start Test"))
        self.clearGraphs.setText(_translate("DataResamplingTools", "Clear"))
        self.label_65.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.label_65.setText(_translate("DataResamplingTools", "Choose sampling algorithm:"))
        self.label_67.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.label_67.setText(_translate("DataResamplingTools", "Progress standard classification:"))
        self.label_66.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.label_66.setText(_translate("DataResamplingTools", "Number of Folds (CV):"))
        self.label_68.setToolTip(_translate("DataResamplingTools", "Only csv datasets are acceptable!"))
        self.label_68.setText(_translate("DataResamplingTools", "Progress classification resampled data:"))
        self.groupBox_4.setTitle(_translate("DataResamplingTools", "Tests Results"))
        self.label_69.setText(_translate("DataResamplingTools", "Classification results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.testsTab), _translate("DataResamplingTools", "Experiments"))
